apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-repo-uploads
  labels:
    app: knowledge-repo-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
